<a href="https://colab.research.google.com/github/ANUJT65/colabfiles/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [1]:
!nvidia-smi


Fri Dec  8 09:57:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [24]:
import torch
torch.cuda.is_available()

True

In [25]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [26]:
torch.cuda.device_count()

1

In [27]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [29]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

**pytorch tensors are created using torch.Tensor()**


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim
#no dimensions as scalar is one direction

0

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim
#1 dimension vector with direction and magnitude

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [ ]:
### creating a tensor


creating a tensor

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [13]:
TENSOR.ndim
#number of square brackets = dimensions

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

**Random tensors  neural networks work on these random tensors. Star with random numbers> look at data >> update random numbers >> look at data and update the random nos
**

In [16]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.4340, 0.0748, 0.2383, 0.5099],
        [0.5998, 0.5852, 0.6825, 0.0618],
        [0.5611, 0.0585, 0.2273, 0.9642]])

In [17]:
random_tensor.dtype

torch.float32

In [22]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [30]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor.ndim

1

In [33]:
tensor * tensor

tensor([1, 4, 9])

In [34]:
torch.matmul(tensor,tensor)

tensor(14)

In [35]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)


In [36]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [38]:
torch.mm(tensor_A, tensor_B.T)
#we multiply with the transpose of b as it causes error with original
#neural netoworks are full of matrix multiplications and dot products

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])