<a href="https://colab.research.google.com/github/ANUJT65/colabfiles/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [2]:
!nvidia-smi


Sun Dec 10 08:43:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
torch.cuda.device_count()

1

In [6]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [7]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

**pytorch tensors are created using torch.Tensor()**


In [8]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim
#no dimensions as scalar is one direction

0

In [10]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim
#1 dimension vector with direction and magnitude

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
### creating a tensor


creating a tensor

In [16]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [17]:
TENSOR.ndim
#number of square brackets = dimensions

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

**Random tensors  neural networks work on these random tensors. Star with random numbers> look at data >> update random numbers >> look at data and update the random nos
**

In [19]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.1439, 0.6865, 0.5109, 0.8682],
        [0.3543, 0.3279, 0.2056, 0.2495],
        [0.9411, 0.2675, 0.0811, 0.3577]])

In [20]:
random_tensor.dtype

torch.float32

In [21]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [23]:
tensor = torch.tensor([1, 2, 3])
tensor.ndim

1

In [24]:
tensor * tensor

tensor([1, 4, 9])

In [25]:
torch.matmul(tensor,tensor)

tensor(14)

In [26]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)



A and B to be multiplied (where A has dimensions m x n and B has dimensions n x p, the number of columns in the first matrix (A) must be equal to the number of rows in the second matrix (B). The resulting matrix will have dimensions m x p.

In [27]:
print(tensor_A)
print(tensor_B.T)
#A and B to be multiplied (where A has dimensions m x n and B has dimensions n x p), the number of columns in the first matrix (A) must be equal to the number of rows in the second matrix (B). The resulting matrix will have dimensions m x p.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [28]:
torch.mm(tensor_A, tensor_B.T)
#we multiply with the transpose of b as it causes error with original
#neural netoworks are full of matrix multiplications and dot products

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [29]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor - 10

tensor([-9, -8, -7])

**FIND MAX MIN MEAN SUM **

In [33]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
x.dtype
#cannot work with int64

torch.int64

In [38]:
torch.mean(x.type(torch.float64))
#mean only works with float

tensor(45., dtype=torch.float64)

In [41]:
x.sum()

tensor(450)

In [42]:
x.max()


tensor(90)

In [43]:
x.min()

tensor(0)

** POSITIONAL ARGUMENTS OR INDEX FINDING**

---



---



In [46]:
x.argmax()

tensor(9)

In [47]:
x.argmin()

tensor(0)

**new shaping and sqeezing**

In [49]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [50]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape
#removed 8

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [51]:
z = x.view(1, 7)
z, z.shape
#view command

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

**If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().**

In [58]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

**NUMPY TORCH INTEGRATION**

In [59]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [60]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [63]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_B == random_tensor_A

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

**RANDOM SEEDS**

---



---
TO EQUATE RANDOMNESS.



In [64]:
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

In [65]:
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)


In [66]:
print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])